export const skills = [
    {tool: "Python", number: 10, group: "Language"},
    {tool: "Golang", number: 9, group: "Language"},
    {tool: "Typescript", number: 8, group: "Language"},
    {tool: "Javascript", number: 7, group: "Language"},
    {tool: "SQL (Transact)", number: 10, group: "Language"},
    {tool: "SQL (PL)", number: 8, group: "Language"},
    {tool: "Cipher", number: 8, group: "Language"},
    {tool: "G-SQL", number: 9, group: "Language"},

    {tool: "Faiss", number: 9, group: "AI"},
    {tool: "NMSLIB", number: 8, group: "AI"},
    {tool: "Hugging Face", number: 9, group: "AI"},
    {tool: "Torch", number: 9, group: "AI"},
    {tool: "Tensorflow", number: 9, group: "AI"},
    {tool: "Comet M", number: 10, group: "AI"},
    {tool: "SageMaker", number: 7, group: "AI"},
    {tool: "Snorkel.ai", number: 6, group: "AI"},

    {tool: "FastAPIi", number: 10, group: "API"},
    {tool: "Flask", number: 10, group: "API"},
    {tool: "Mux", number: 9, group: "API"},
    {tool: "FastHTTP", number: 4, group: "API"},
    {tool: "GraphQL", number: 8, group: "API"},
    {tool: "Apigee", number: 8, group: "API"},

    {tool: "Docker", number: 10, group: "Containers"},
    {tool: "Kubernetes", number: 9, group: "Containers"},
    {tool: "EKS", number: 10, group: "Containers"},
    {tool: "Skaffold", number: 9, group: "Containers"},
    {tool: "Kaniko", number: 9, group: "Containers"},
    {tool: "Helm", number: 10, group: "Containers"},
    {tool: "Rancher", number: 8, group: "Containers"},
    {tool: "Harbor", number: 7, group: "Containers"},
    {tool: "Argo", number: 7, group: "Containers"},

    {tool: "Tableau", number: 10, group: "Data Analytic | Visualization"},
    {tool: "Kibana", number: 10, group: "Data Analytic | Visualization"},
    {tool: "d3.js", number: 8, group: "Data Analytic | Visualization"},
    {tool: "PowerBI", number: 10, group: "Data Analytic | Visualization"},
    {tool: "Grafana", number: 8, group: "Data Analytic | Visualization"},
    {tool: "Superset", number: 8, group: "Data Analytic | Visualization"},

    {tool: "Jenkins", number: 10, group: "CI/CD"},
    {tool: "Spinnaker", number: 9, group: "CI/CD"},
    {tool: "Github Actions", number: 10, group: "CI/CD"},
    {tool: "TravisCI", number: 10, group: "CI/CD"},

    {tool: "TigerGraph", number: 8, group: "Database"},
    {tool: "neo4j", number: 10, group: "Database"},
    {tool: "Postgres", number: 10, group: "Database"},
    {tool: "Elasticsearch", number: 10, group: "Database"},
    {tool: "MongoDB", number: 7, group: "Database"},
    {tool: "Cassandra", number: 10, group: "Database"},
    {tool: "DynamoDB", number: 10, group: "Database"},
    {tool: "SQL Server", number: 10, group: "Database"},
    {tool: "Redis", number: 7, group: "Database"},
    {tool: "Oracle", number: 5, group: "Database"},

    {tool: "Svelte", number: 6, group: "Front End"},
    {tool: "SvelteKit", number: 6, group: "Front End"},
    {tool: "tailwindcss", number: 7, group: "Front End"},
    {tool: "React", number: 5, group: "Front End"},

    {tool: "AWS", number: 8, group: "Cloud"},
    {tool: "Azure", number: 6, group: "Cloud"},
    {tool: "Terraform", number: 10, group: "IaC"},
]

export const work = [
    {name: "JP Morgan Chase", light: "/images/icons/jpm.svg", dark: "/images/icons/JPM_BIG.D.svg", dates: "2021 - Present"},
    {name: "BNP Paribas NA", light: "/images/icons/BNP.PA_BIG.svg", dark: "/images/icons/BNP.PA_BIG.D.svg", dates: "2015 - 2021"},
    {name: "UBS Securities", light: "/images/icons/UBS_BIG.svg", dark: "/images/icons/UBS_BIG.D.svg", dates: "2013 - 2015"},
]

